const STORAGE_KEY='mathTutorProgressV1';
const defaultState={xp:0,level:1,streak:0,totalMinutes:0,sessions:0,lastPractice:null,lessonStep:0,lessonDone:false,achievements:[],topics:{fractions:{name:'Дроби',done:0,correct:0,wrong:0,hints:0,difficulty:1,last:null},percent:{name:'Проценты',done:0,correct:0,wrong:0,hints:0,difficulty:1,last:null}},recent:[]};
let state=loadState();
let practice={mode:'fractions',question:null,attempts:0,hints:0};
let lesson={step:state.lessonDone?4:0,attempts:0,hints:0};
const views=document.querySelectorAll('.view');
const navItems=document.querySelectorAll('.nav-item');
const sidebar=document.querySelector('.sidebar');
const titles={home:'Привет!',lesson:'Урок дня',practice:'Практика',chat:'Спросить репетитора',progress:'Мой прогресс',parent:'Кабинет родителя'};

function loadState(){try{return {...defaultState,...JSON.parse(localStorage.getItem(STORAGE_KEY)||'{}')}}catch{return structuredClone(defaultState)}}
function saveState(){localStorage.setItem(STORAGE_KEY,JSON.stringify(state));updateChrome()}
function updateChrome(){document.getElementById('xp-count').textContent=state.xp;document.querySelector('.sidebar-footer strong').textContent=`${state.streak} дня подряд`}
function toast(message){const el=document.getElementById('toast');el.textContent=message;el.classList.add('show');clearTimeout(toast.timer);toast.timer=setTimeout(()=>el.classList.remove('show'),2200)}
function showView(name){
  views.forEach(v=>v.classList.toggle('active',v.id===`view-${name}`));
  navItems.forEach(n=>n.classList.toggle('active',n.dataset.view===name));
  document.getElementById('page-title').textContent=titles[name];
  sidebar.classList.remove('open');
  if(name==='lesson')renderLesson(); if(name==='practice')renderPractice(); if(name==='chat')renderChat(); if(name==='progress')renderProgress(); if(name==='parent')renderParent();
  window.scrollTo({top:0,behavior:'smooth'});
}
navItems.forEach(item=>item.addEventListener('click',()=>showView(item.dataset.view)));
document.querySelectorAll('[data-start-lesson]').forEach(btn=>btn.addEventListener('click',()=>showView('lesson')));
document.querySelectorAll('[data-view-button]').forEach(btn=>btn.addEventListener('click',()=>showView(btn.dataset.viewButton)));
document.getElementById('mobile-menu').addEventListener('click',()=>sidebar.classList.toggle('open'));

const lessonSteps=[
 {label:'Объяснение',title:'Зачем нужен общий знаменатель?',body:`<p class="lead">Складывать можно только одинаковые доли. Представь две дорожки в игровом парке: одну разделили на 3 равные части, другую — на 6.</p><div class="fraction-bars"><div><b>⅓</b><span class="bar thirds"><i></i><i></i><i></i></span></div><div><b>²⁄₆</b><span class="bar sixths"><i></i><i></i><i></i><i></i><i></i><i></i></span></div></div><div class="insight"><span>!</span><p><strong>⅓ и ²⁄₆ — одна и та же часть.</strong><br>Мы раздробили каждую треть ещё пополам. Теперь доли одинакового размера.</p></div>`},
 {label:'Пример',title:'Решим вместе: ⅔ + ⅙',body:`<p class="lead">Знаменатели 3 и 6. Сделаем третьи доли шестыми.</p><ol class="steps-list"><li><span>1</span><div>Общий знаменатель — <strong>6</strong>.</div></li><li><span>2</span><div>Умножаем числитель и знаменатель ⅔ на 2:<br><strong>⅔ = ⁴⁄₆</strong></div></li><li><span>3</span><div>Складываем одинаковые доли:<br><strong>⁴⁄₆ + ⅙ = ⁵⁄₆</strong></div></li></ol>`},
 {label:'Вместе',title:'Твоя очередь: ½ + ⅓',body:`<p class="lead">В игровом парке ½ территории заняли аттракционы, а ⅓ — дорожки. Какая часть территории занята?</p><div class="question-box"><div class="big-equation">½ + ⅓ = ?</div><label for="lesson-answer">Запиши дробь через /</label><div class="answer-row"><input id="lesson-answer" inputmode="text" autocomplete="off" placeholder="например, 3/4"><button class="primary-btn purple" id="lesson-check">Проверить</button></div><div id="lesson-feedback" class="feedback" aria-live="polite"></div><button class="hint-btn" id="lesson-hint">◇ Нужна подсказка</button></div>`},
 {label:'Закрепление',title:'Проверь понимание',body:`<p class="lead">Почему нельзя сразу сложить числители и знаменатели в примере ½ + ⅓?</p><div class="choice-list"><button data-understanding="wrong">Получится слишком большое число</button><button data-understanding="right">Доли разного размера, сначала их нужно сделать одинаковыми</button><button data-understanding="wrong">Такое сложение всегда запрещено</button></div><div id="understanding-feedback" class="feedback" aria-live="polite"></div>`},
 {label:'Готово',title:'Миссия выполнена!',body:`<div class="success-scene"><div class="success-badge">✓</div><h3>Ты разобралась с общим знаменателем</h3><p>Сегодня ты не просто решила пример — ты поняла, зачем нужны одинаковые доли.</p><div class="reward-row"><span>+30 XP</span><span>15 минут</span><span>1 новая тема</span></div><button class="primary-btn purple" data-go-practice>Закрепить в практике →</button></div>`}
];
function renderLesson(){
 const s=lessonSteps[lesson.step];
 document.getElementById('view-lesson').innerHTML=`<div class="lesson-layout"><article class="learning-card"><div class="lesson-progress"><span>Шаг ${lesson.step+1} из 5 · ${s.label}</span><div><i style="width:${(lesson.step+1)*20}%"></i></div></div><h2>${s.title}</h2>${s.body}<div class="lesson-nav">${lesson.step>0&&lesson.step<4?'<button class="secondary-btn" id="lesson-prev">← Назад</button>':''}${lesson.step<2?'<button class="primary-btn purple" id="lesson-next">Понятно, дальше →</button>':''}</div></article><aside class="tutor-note"><div class="tutor-avatar">π</div><span class="eyebrow">РЕПЕТИТОР РЯДОМ</span><p>${lesson.step===2?'Если сложно — это нормально. Подсказка не отнимает награду за старание.':'Не спеши. Важно понять каждый шаг, а не решить быстрее всех.'}</p></aside></div>`;
 bindLesson();
}
function bindLesson(){
 document.getElementById('lesson-next')?.addEventListener('click',()=>{lesson.step++;renderLesson()});
 document.getElementById('lesson-prev')?.addEventListener('click',()=>{lesson.step--;renderLesson()});
 document.getElementById('lesson-hint')?.addEventListener('click',()=>{lesson.hints++;const f=document.getElementById('lesson-feedback');f.className='feedback hint';f.innerHTML=lesson.hints===1?'Подумай: какое самое маленькое число делится и на 2, и на 3?': 'Это число 6. Преврати ½ в шестые и ⅓ в шестые.'});
 document.getElementById('lesson-check')?.addEventListener('click',()=>{
   const value=document.getElementById('lesson-answer').value.trim(); const f=document.getElementById('lesson-feedback'); lesson.attempts++;
   if(equivalent(value,'5/6')){f.className='feedback good';f.innerHTML='<strong>Да, ⁵⁄₆!</strong> Отлично: ты сделала доли одинаковыми.';setTimeout(()=>{lesson.step=3;renderLesson()},900)}
   else{f.className='feedback hint';f.textContent=lesson.attempts===1?'Почти. Сначала найди общий знаменатель для 2 и 3. Какое число подойдёт?':'Общий знаменатель — 6. Тогда ½ = ³⁄₆, а ⅓ = ²⁄₆. Что получится при сложении?'}
 });
 document.querySelectorAll('[data-understanding]').forEach(b=>b.addEventListener('click',()=>{const f=document.getElementById('understanding-feedback');if(b.dataset.understanding==='right'){f.className='feedback good';f.textContent='Точно! Складываем только одинаковые по размеру доли.';finishLesson()}else{f.className='feedback hint';f.textContent='Подумаем о кусочках: половина и треть — одинакового размера или разного?'}}));
 document.querySelector('[data-go-practice]')?.addEventListener('click',()=>showView('practice'));
}
function finishLesson(){if(!state.lessonDone){state.lessonDone=true;state.xp+=30;state.sessions++;state.totalMinutes+=15;state.recent.unshift({date:new Date().toLocaleDateString('ru-RU',{day:'numeric',month:'short'}),title:'Общий знаменатель',result:'Поняла принцип',minutes:15});saveState();toast('Награда: +30 XP')}setTimeout(()=>{lesson.step=4;renderLesson()},850)}

const banks={
 fractions:[
  {d:1,q:'Половина из 18 игровых блоков — это сколько?',a:'9',h:['Раздели 18 на 2.','Сколько будет 18 ÷ 2?'],why:'½ числа означает разделить его на 2.'},
  {d:1,q:'Сократи дробь 6/8.',a:'3/4',h:['Найди число, на которое делятся и 6, и 8.','Раздели числитель и знаменатель на 2.'],why:'6/8 = 3/4 после деления обеих частей на 2.'},
  {d:2,q:'Вычисли: 1/4 + 2/4.',a:'3/4',h:['Знаменатели уже одинаковые.','Сложи числители, а знаменатель оставь 4.'],why:'Когда доли одинаковы, складываем их количество: 1 + 2.'},
  {d:2,q:'Вычисли: 2/3 + 1/6.',a:'5/6',h:['Общий знаменатель для 3 и 6 — 6.','2/3 = 4/6. Теперь прибавь 1/6.'],why:'2/3 превратили в 4/6 и сложили одинаковые доли.'},
  {d:3,q:'Найди 3/8 от 24 ресурсов.',a:'9',h:['Сначала найди 1/8 от 24.','24 ÷ 8 = 3, затем умножь на 3.'],why:'Чтобы найти 3/8 числа, делим на 8 и умножаем на 3.'}
 ],
 percent:[
  {d:1,q:'Найди 10% от 70 монет.',a:'7',h:['10% — это одна десятая.','Раздели 70 на 10.'],why:'10% числа находим делением на 10.'},
  {d:1,q:'Найди 50% от 36 блоков.',a:'18',h:['50% — это половина.','Раздели 36 на 2.'],why:'50% всегда равны половине числа.'},
  {d:2,q:'Предмет стоил 80 монет. Скидка 25%. Сколько монет составляет скидка?',a:'20',h:['25% — это четверть.','Раздели 80 на 4.'],why:'25% = 1/4, поэтому 80 ÷ 4 = 20.'},
  {d:2,q:'Найди 15% от 200.',a:'30',h:['Разложи 15% на 10% и 5%.','10% от 200 = 20, а 5% = 10. Сложи.'],why:'15% = 10% + 5%, значит 20 + 10 = 30.'},
  {d:3,q:'После скидки 20% предмет стоит 120 монет. Сколько он стоил раньше?',a:'150',h:['После скидки осталось 80% цены.','120 — это 80%. Найди 10%, затем 100%.'],why:'120 ÷ 8 × 10 = 150.'}
 ]
};
function chooseQuestion(mode){const key=mode==='weak'?weakTopic():mode;const t=state.topics[key];const options=banks[key].filter(q=>q.d===t.difficulty);const pool=options.length?options:banks[key];return {...pool[Math.floor(Math.random()*pool.length)],topic:key}}
function weakTopic(){return Object.entries(state.topics).sort((a,b)=>(b[1].wrong/(b[1].done||1))-(a[1].wrong/(a[1].done||1)))[0][0]}
function renderPractice(){
 if(!practice.question){document.getElementById('view-practice').innerHTML=`<div class="intro-row"><div><span class="eyebrow">ВЫБЕРИ РЕЖИМ</span><h2>Что потренируем?</h2><p>Задания подстроятся под твой текущий уровень.</p></div></div><div class="mode-grid"><button data-mode="fractions"><span class="mode-icon purple">½</span><strong>Дроби</strong><small>Уровень ${state.topics.fractions.difficulty} из 3</small></button><button data-mode="percent"><span class="mode-icon blue">%</span><strong>Проценты</strong><small>Уровень ${state.topics.percent.difficulty} из 3</small></button><button data-mode="mixed"><span class="mode-icon amber">✦</span><strong>Смешанная</strong><small>Разные темы</small></button><button data-mode="weak"><span class="mode-icon rose">↻</span><strong>Слабые темы</strong><small>По прошлым ошибкам</small></button></div>`;document.querySelectorAll('[data-mode]').forEach(b=>b.addEventListener('click',()=>startPractice(b.dataset.mode)));return}
 const q=practice.question;document.getElementById('view-practice').innerHTML=`<div class="practice-wrap"><div class="practice-meta"><button class="back-link" id="practice-back">← Режимы</button><span>${q.topic==='fractions'?'Дроби':'Проценты'} · уровень ${q.d}</span></div><article class="practice-card"><div class="question-number">ЗАДАНИЕ</div><h2>${q.q}</h2><label for="practice-answer">Твой ответ</label><div class="answer-row"><input id="practice-answer" inputmode="text" autocomplete="off" placeholder="Введи ответ"><button class="primary-btn purple" id="practice-check">Проверить</button></div><div id="practice-feedback" class="feedback" aria-live="polite"></div><button class="hint-btn" id="practice-hint">◇ Взять подсказку</button></article><aside class="mini-rule"><span>Помни</span><p>Ошибаться можно. Репетитор сначала поможет найти следующий шаг.</p></aside></div>`;bindPractice()
}
function startPractice(mode){practice={mode,question:chooseQuestion(mode==='mixed'?(Math.random()>.5?'fractions':'percent'):mode),attempts:0,hints:0};renderPractice()}
function bindPractice(){
 document.getElementById('practice-back').addEventListener('click',()=>{practice.question=null;renderPractice()});
 document.getElementById('practice-hint').addEventListener('click',()=>{practice.hints=Math.min(2,practice.hints+1);const f=document.getElementById('practice-feedback');f.className='feedback hint';f.textContent=practice.question.h[practice.hints-1];state.topics[practice.question.topic].hints++;saveState()});
 document.getElementById('practice-check').addEventListener('click',()=>{const v=document.getElementById('practice-answer').value.trim();const f=document.getElementById('practice-feedback');practice.attempts++;if(equivalent(v,practice.question.a)){f.className='feedback good';f.innerHTML=`<strong>Верно!</strong> ${practice.question.why}<br><button class="inline-next" id="next-question">Следующее задание →</button>`;recordPractice(true);document.getElementById('next-question').addEventListener('click',()=>{practice.question=chooseQuestion(practice.mode==='mixed'?(Math.random()>.5?'fractions':'percent'):practice.mode);practice.attempts=0;practice.hints=0;renderPractice()})}else{f.className='feedback hint';f.textContent=practice.attempts===1?practice.question.h[0]:practice.question.h[1];if(practice.attempts===2)recordPractice(false)}})
}
function recordPractice(correct){const t=state.topics[practice.question.topic];t.done++;t[correct?'correct':'wrong']++;t.last=new Date().toISOString();state.lastPractice=t.last;if(correct){state.xp+=10;if(t.correct>=t.wrong+4)t.difficulty=Math.min(3,t.difficulty+1)}else if(t.wrong>t.correct/2)t.difficulty=Math.max(1,t.difficulty-1);saveState()}
function equivalent(value,target){const norm=s=>String(s).replace(',','.').replace(/\s/g,'');const val=norm(value),tar=norm(target);if(val===tar)return true;const frac=s=>{if(!s.includes('/'))return Number(s);const [a,b]=s.split('/').map(Number);return b?a/b:NaN};return Number.isFinite(frac(val))&&Math.abs(frac(val)-frac(tar))<.0001}

function renderChat(){document.getElementById('view-chat').innerHTML=`<div class="chat-shell"><div class="chat-info"><div class="tutor-avatar large">π</div><div><h2>Репетитор Луми</h2><p>Поможет разобраться, но не сделает домашнюю работу вместо тебя.</p></div></div><div class="quick-prompts"><button>Объясни общий знаменатель</button><button>Как найти процент?</button><button>Дай похожий пример</button></div><div class="messages" id="messages"><div class="message tutor"><span>π</span><p>Привет! С чем разберёмся? Можешь написать пример или тему, которая кажется сложной.</p></div></div><form class="chat-form" id="chat-form"><input id="chat-input" aria-label="Вопрос репетитору" placeholder="Напиши вопрос…" autocomplete="off"><button aria-label="Отправить">↑</button></form></div>`;bindChat()}
function bindChat(){document.querySelectorAll('.quick-prompts button').forEach(b=>b.addEventListener('click',()=>sendChat(b.textContent)));document.getElementById('chat-form').addEventListener('submit',e=>{e.preventDefault();sendChat(document.getElementById('chat-input').value)})}
function sendChat(text){text=text.trim();if(!text)return;const m=document.getElementById('messages');m.insertAdjacentHTML('beforeend',`<div class="message user"><p>${escapeHtml(text)}</p></div>`);document.getElementById('chat-input').value='';setTimeout(()=>{m.insertAdjacentHTML('beforeend',`<div class="message tutor"><span>π</span><p>${tutorReply(text)}</p></div>`);m.scrollTop=m.scrollHeight},350);m.scrollTop=m.scrollHeight}
function tutorReply(text){const t=text.toLowerCase();if(/реши|ответ|домаш/.test(t))return 'Я помогу решить самостоятельно. Напиши, какой первый шаг ты уже попробовала сделать?';if(/знаменател/.test(t))return 'Знаменатель показывает размер долек. Чтобы сложить дроби, дольки должны быть одинаковыми. Какое самое маленькое число делится на оба знаменателя в твоём примере?';if(/процент|%/.test(t))return 'Процент — это одна сотая часть. Начнём с удобного: 10% можно найти, разделив число на 10. От какого числа нужно найти процент?';if(/пример|похож/.test(t))return 'Попробуй: 1/2 + 1/4. Сначала скажи, во что превратится 1/2, если знаменатель станет 4?';if(/не понимаю|сложно/.test(t))return 'Давай сделаем шаг меньше. Что именно сбивает: правило, вычисления или непонятно, с чего начать?';return 'Покажи пример или расскажи, на каком шаге остановилась. Я задам вопрос, который поможет двинуться дальше.'}
function escapeHtml(s){return s.replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}

function renderProgress(){const f=state.topics.fractions,p=state.topics.percent;document.getElementById('view-progress').innerHTML=`<div class="stats-grid"><article><span class="eyebrow">ОБЩИЙ УРОВЕНЬ</span><strong>${state.level}</strong><p>${state.xp} XP набрано</p></article><article><span class="eyebrow">ЗАНЯТИЙ</span><strong>${state.sessions}</strong><p>${state.totalMinutes} минут</p></article><article><span class="eyebrow">СЕРИЯ</span><strong>${state.streak}</strong><p>дня подряд</p></article></div><div class="progress-layout"><article class="panel"><div class="section-heading compact"><div><span class="eyebrow">КАРТА ТЕМ</span><h2>Учебный маршрут</h2></div></div>${topicProgress(f,'0','purple')}${topicProgress(p,'0','blue')}<div class="skill-map"><div class="map-item active"><span>1</span><div><strong>Смысл дроби</strong><small>Начинаем здесь</small></div></div><div class="map-item"><span>2</span><div><strong>Общий знаменатель</strong><small>Следующий этап</small></div></div><div class="map-item"><span>3</span><div><strong>Процент от числа</strong><small>Впереди</small></div></div><div class="map-item"><span>4</span><div><strong>Число по проценту</strong><small>Впереди</small></div></div></div></article><article class="panel"><span class="eyebrow">ДОСТИЖЕНИЯ</span><h2>Награды за понимание</h2><div class="badges"><div><span>◇</span><strong>Первый шаг</strong><small>Откроется после занятия</small></div><div><span>↻</span><strong>Не сдалась</strong><small>Откроется после исправления</small></div><div><span>✦</span><strong>Своя мысль</strong><small>Откроется после объяснения</small></div></div></article></div>`}
function topicProgress(t,pct,color){const accuracy=Math.round(t.correct/(t.done||1)*100);return `<div class="topic-progress"><div><span class="topic-icon ${color}">${t.name==='Дроби'?'½':'%'}</span><div><strong>${t.name}</strong><small>${t.done} заданий · ${accuracy}% верно</small></div></div><span>уровень ${t.difficulty}/3</span></div>`}
function renderParent(){const total=Object.values(state.topics).reduce((a,t)=>a+t.done,0);const correct=Object.values(state.topics).reduce((a,t)=>a+t.correct,0);const accuracy=total?Math.round(correct/total*100):0;const hasData=state.sessions>0||total>0;const bars=hasData?[35,70,20,85,50,65,40]:[4,4,4,4,4,4,4];document.getElementById('view-parent').innerHTML=`<div class="parent-banner"><div><span class="eyebrow">ОБЗОР ОБУЧЕНИЯ</span><h2>${hasData?'Появились первые результаты':'Данных пока нет'}</h2><p>${hasData?'Отчёт обновляется после каждого урока и практики.':'Завершите первое занятие — здесь появятся сильные стороны, сложности и рекомендации.'}</p></div><div class="parent-score"><strong>${accuracy}%</strong><span>точность</span></div></div><div class="parent-grid"><article class="panel"><span class="eyebrow">АКТИВНОСТЬ</span><h3>${state.sessions} занятий · ${state.totalMinutes} минут</h3><div class="week-chart">${bars.map((h,i)=>`<div><i style="height:${h}%"></i><span>${['Пн','Вт','Ср','Чт','Пт','Сб','Вс'][i]}</span></div>`).join('')}</div></article><article class="panel"><span class="eyebrow">СИЛЬНЫЕ СТОРОНЫ</span><p>${hasData?'Формируются по правильным ответам и самостоятельным решениям.':'Появятся после первой практики.'}</p></article><article class="panel"><span class="eyebrow">ТРЕБУЕТ ВНИМАНИЯ</span><p>${hasData?'Определяется по повторяющимся ошибкам и использованным подсказкам.':'Пока недостаточно данных.'}</p></article><article class="recommend-card"><span>Рекомендация</span><h3>${hasData?'Продолжить с текущего уровня':'Начать с короткого урока по дробям'}</h3><p>Следующее задание подбирается автоматически по результатам.</p><button class="secondary-btn" id="parent-weak">Открыть практику →</button></article></div><article class="panel recent-panel"><div><span class="eyebrow">ПОСЛЕДНИЕ ЗАНЯТИЯ</span><h2>История</h2></div>${state.recent.length?state.recent.slice(0,5).map(x=>`<div class="history-row"><strong>${x.date}</strong><span>${x.title}</span><span>${x.minutes} минут</span><em>${x.result}</em></div>`).join(''):'<p>История появится после первого завершённого занятия.</p>'}</article>`;document.getElementById('parent-weak').addEventListener('click',()=>{showView('practice');startPractice('weak')})}

function registerWebMCP(){const ctx=document.modelContext;if(!ctx?.registerTool)return;try{ctx.registerTool({name:'start_math_practice',title:'Начать практику',description:'Открывает практику по выбранной теме в приложении.',inputSchema:{type:'object',properties:{topic:{type:'string',enum:['fractions','percent','weak']}},required:['topic'],additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:false},execute(input){if(!['fractions','percent','weak'].includes(input?.topic))throw new Error('Неизвестная тема');showView('practice');startPractice(input.topic);return {started:true,topic:input.topic}}})}catch(e){console.debug('WebMCP unavailable',e)}}
updateChrome();registerWebMCP();
